### ISSUE TITLE
One extra log block is present on one of the sides of the pillager outpost

### ISSUE THREAD

**Issue by WitheredWasabi** [minecraftabnormals/Savage-and-Ravage#24]
![image](https://user-images.githubusercontent.com/38932715/89609367-7ddcbb80-d82c-11ea-9a51-74ec8d18ad62.png)

**Comment by Farcr** [comment]
fuck you tess why do i have to be the one that fixes this. you ruined my life killed my family. lost all my money. i have nothing because of you.
