### ISSUE TITLE
1.16.1 Invisible Pillagers?

### ISSUE THREAD

**Issue by ProfEnd** [minecraftabnormals/Savage-and-Ravage#28]
Running a server using latest forge build, some players experienced invisible pillagers, not sure of the cause or conditions. When they died, they were sometimes able to see them again. Mod-list is [attached.](https://drive.google.com/file/d/1ak_hHMAQe1g-P6jp-JD5lzw5brTMZo_0/view?usp=sharing)

**Comment by bageldotjpg** [comment]
Haven't been able to reproduce. If you can still reproduce it, feel free to post a log and reopen
