### ISSUE TITLE
server crash when looking at a piliger

### ISSUE THREAD

**Issue by w0lf-m4n** [minecraftabnormals/Savage-and-Ravage#30]
my modded Minecraft server crashes when looking at a piliger
or when a pillager fires an arrow I can't really tell

**Comment by tessdotcpp** [comment]
Could you post a crash report?

**Comment by tessdotcpp** [comment]
yeah i didn't fix it yet sorry lol

**Comment by bageldotjpg** [comment]
Feel free to reopen this with more information
