### ISSUE TITLE
Skeleton Villager Spawning

### ISSUE THREAD

**Issue by tikiMC** [minecraftabnormals/Savage-and-Ravage#36]
I'm running Biomes O' Plenty with Savage & Ravage and the Rainbow Valley biome which is intended to act like the mushroom island biome where no hostile mobs spawn, has skeleton villagers in it. They are the only hostile mob which is very annoying.

**Comment by abigailfails** [comment]
OK now it was [actually](https://github.com/minecraftabnormals/Savage-and-Ravage/commit/3f3209e3f86cbcdbf4f9987a34264cd6a4e12a07) fixed. I don't like this solution but it works for now, maybe something better can be come up on forstride's end.
