### ISSUE TITLE
Pillagers turn invisible when using this mod?

### ISSUE THREAD

**Issue by winterdrake** [minecraftabnormals/Savage-and-Ravage#38]
I'm using a modpack with this mod, Quark, and a few of Quark's "friends" mods. So I can't say for certain that this is caused by this mod, but I have noticed mutiple instances where I was being shot at by invisible pillagers, and an invisible witch during a raid. Disconnecting and reconnecting from the server fixed this. 

I assume that since this is a pillager issue, it may come from the mod that overhauls pillagers? If I'm wrong, let me know, and if you have any idea what might be causing the issue. Also using optifine but I've never had any issues with it.

This is all on 1.16.1.

Great mod, by the way. Controvertial name aside, I really like the content and creative mobs you've added!

**Comment by bageldotjpg** [comment]
> Also using optifine but I've never had any issues with it.
Doesn't mean they won't happen, still could likely be them
>  Controvertial name aside,
What's controversial about it...?

And to get more info, can you provide your latest.log file and debug.log file next time you witness this, and also maybe provide your mod list, as I see no reason why this would be occurring and it has never happened to me.
Thanks!

**Comment by winterdrake** [comment]
I will grab those log files as soon as it happens again! It may just be something broken with forge beta, or something screwy with mod interactions, but I figured I would at least try reporting.

As far as my mention about the name being controvertial, the term "S*vage" is considered highly politically incorrect due to its historical usage of [dehumanizing indigenous people.](https://www.google.com/search?q=dont%27+use+the+word+savage&rlz=1C1CHBF_enUS810US810&oq=dont%27+use+the+word+savage&aqs=chrome..69i57j33i22i29i30l3.2520j0j7&sourceid=chrome&ie=UTF-8)

**Comment by bageldotjpg** [comment]
That's definitely not the usage of the word here, and I've actually never seen anyone that so I wouldn't consider it "highly" politically incorrect.
If used in the nature that you're describing, yes, but it's a commonly used word, and by definition, savage means "(of an animal or force of nature) fierce, violent, and uncontrolled." - like how Illagers will tear down a village violently.

**Comment by bageldotjpg** [comment]
Just discovered this is a possible Optifine bug
